### ISSUE TITLE
A huge thank you

### ISSUE THREAD

**Issue by vvo** [serkan-ozal/middy-profiler#2]
Your module saved me hours of debugging and I could pinpoint my AWS lambda issue. Not only that but I know I'll be able to do it again now, whenever I want to find performance issues of a live Lambda.

PS: I believe there's a huge opportunity for making a standalone version of this module, that can be used locally and most importantly without middy (so it's easier to use).

BTW: what other perf tooling have you used locally? Thanks!

Ref: https://twitter.com/vvoyer/status/1498436054851981320

**Comment by serkan-ozal** [comment]
Hi @vvo, 

Happy to hear that middy-profiler has helped to troubleshot a performance issue which is hard to identify by an APM tool.

Making this project `middy` independent totally makes sense to me. I will keep you updated once I published/released standalone version.

Additionally, as I am CTO&Founder of [Thundra](https://www.thundra.io/apm) (APM for serverless centric workloads), I am also thinking of adding such profiling capability to Thundra APM platform in addition to Thundra's advanced tracing capabilities. 

Do you think that might it (CPU profiler) be super useful for people working on performance issues on AWS Lambda?

**Comment by KillDozerX2** [comment]
This helped so much, thank you. @vvo I think your example should be put up as a case study in this repo.

**Comment by serkan-ozal** [comment]
Hi @vvo,

I have added standalone mode support to be able to use `middy-profiler` without `middy` framework. You can check [Standalone Usage (without Middy)](https://github.com/serkan-ozal/middy-profiler/blob/master/README.md#standalone-usage-without-middy) section for the usage.

**Comment by serkan-ozal** [comment]
Hi @KillDozerX2, 

I have added a link to the @vvo's use-case under [Use Cases](https://github.com/serkan-ozal/middy-profiler/blob/master/README.md#use-cases) section.
