### ISSUE TITLE
Ability to disable profiling

### ISSUE THREAD

**Issue by KillDozerX2** [serkan-ozal/middy-profiler#5]
After using this and being able to figure out multiple points to increase performance, one thing that bugs us is having to remove the profiler before deploying to prod environment.
It would be a great idea to do this so we can set it to false using an env flag in prod.

**Comment by serkan-ozal** [comment]
Hi @KillDozerX2, 

Starting from the version `1.0.4`, you will be able to disable profiler by setting `MIDDY_PROFILER_ENABLE` env var to `false`: https://github.com/serkan-ozal/middy-profiler/blob/master/CHANGELOG.md#104-2022-05-06

**Comment by KillDozerX2** [comment]
Awesome, @serkan-ozal Thank you soo much. I will close this issues
Solved by #6
